"""invoice checkout_session_id

Revision ID: 4bafa6e29c73
Revises: 33f7521db9e0
Create Date: 2026-07-08 06:46:02.035957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bafa6e29c73'
down_revision: Union[str, Sequence[str], None] = '33f7521db9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('checkout_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'checkout_session_id')
    # ### end Alembic commands ###
